version: 2
registries:
  artifact-registry:
    type: npm-registry
    url: https://europe-west1-npm.pkg.dev/join-dev-330413/join/
    username: ${{ secrets.GAR_USERNAME }}
    password: ${{ secrets.GAR_CREDENTIALS }}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    allow:
      - dependency-type: 'production'
    rebase-strategy: 'disabled'
    registries:
      - artifact-registry
    commit-message:
      prefix: "build"
      include: "scope"
